### ISSUE TITLE
FastifyFramework Issue

### ISSUE THREAD

**Issue by tot14883** [H4ad/serverless-adapter#53]
I set my project like below:
but i got error log, I use fastify + AWS CDK + Lambda. How to fix this one?

```import { app } from "./app";
import { ServerlessAdapter } from "@h4ad/serverless-adapter";
import { FastifyFramework } from "@h4ad/serverless-adapter/lib/frameworks/fastify";
import { PromiseResolver } from '@h4ad/serverless-adapter/lib/resolvers/promise';
import { DefaultHandler } from '@h4ad/serverless-adapter/lib/handlers/default';


export const handler = ServerlessAdapter.new(app)
.setFramework(new FastifyFramework())
.setHandler(new DefaultHandler())
.setResolver(new PromiseResolver())
.build();

{
  "errorType": "Error",
  "errorMessage": "SERVERLESS_ADAPTER: Couldn't find adapter to handle this event.",
  "trace": [
    "Error: SERVERLESS_ADAPTER: Couldn't find adapter to handle this event.",
    "    at DefaultHandler2.getAdapterByEventAndContext (/var/task/index.js:48729:17)",
    "    at Runtime.handler (/var/task/index.js:49490:32)",
    "    at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:73:25)"
  ]
}

**Comment by H4ad** [comment]
Hi @tot14883, you need to call `.addAdapter` and add an adapter to handle the AWS event.

If you are using API Gateway V1, see: https://serverless-adapter.viniciusl.com.br/docs/main/adapters/aws/api-gateway-v1#usage
If you are using API Gateway V2, see: https://serverless-adapter.viniciusl.com.br/docs/main/adapters/aws/api-gateway-v2#usage

In the end, your code will look like this:

```ts
import { ServerlessAdapter } from "@h4ad/serverless-adapter";
import { FastifyFramework } from "@h4ad/serverless-adapter/lib/frameworks/fastify";
import { PromiseResolver } from '@h4ad/serverless-adapter/lib/resolvers/promise';
import { DefaultHandler } from '@h4ad/serverless-adapter/lib/handlers/default';
import { ApiGatewayV2Adapter } from '@h4ad/serverless-adapter/lib/adapters/aws';
import { ApiGatewayV1Adapter } from '@h4ad/serverless-adapter/lib/adapters/aws';

export const handler = ServerlessAdapter.new(app)
.setFramework(new FastifyFramework())
.setHandler(new DefaultHandler())
.setResolver(new PromiseResolver())
.addAdapter(new ApiGatewayV1Adapter())
.addAdapter(new ApiGatewayV2Adapter())
.build();
```

You don't need both, but just to show you what you've become.

**Comment by tot14883** [comment]
I follow your solution but i got this error from lambda 

```{
  "errorType": "Error",
  "errorMessage": "SERVERLESS_ADAPTER: Couldn't find adapter to handle this event.",
  "trace": [
    "Error: SERVERLESS_ADAPTER: Couldn't find adapter to handle this event.",
    "    at DefaultHandler2.getAdapterByEventAndContext (/var/task/index.js:48729:17)",
    "    at Runtime.handler (/var/task/index.js:49490:32)",
    "    at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:73:25)"
  ]
}```


```import { app } from "./app";
import { ServerlessAdapter } from "@h4ad/serverless-adapter";
import { FastifyFramework } from "@h4ad/serverless-adapter/lib/frameworks/fastify";
import { PromiseResolver } from '@h4ad/serverless-adapter/lib/resolvers/promise';
import { DefaultHandler } from '@h4ad/serverless-adapter/lib/handlers/default';
import { ApiGatewayV2Adapter } from '@h4ad/serverless-adapter/lib/adapters/aws';

export const handler = ServerlessAdapter.new(app)
.setFramework(new FastifyFramework())
.setHandler(new DefaultHandler())
.setResolver(new PromiseResolver())
.addAdapter(new ApiGatewayV2Adapter())
.build();
```

**Comment by tot14883** [comment]
I see i need to use apigateway-aws-proxy with ApiGatewayV1Adapter(). it works right now!

<img width="221" alt="Screen Shot 2565-09-29 at 15 23 37" src="https://user-images.githubusercontent.com/23735611/192979892-d69f17bb-4aec-4947-8403-58619da95773.png">
